#!/bin/bash

# current Git branch
branch=$(git rev-parse --abbrev-ref HEAD)

# 89, 1, 20
issueNumber=$1

# feature-x-y-z
branchName=$2

# establish branch and tag name variables
releaseBranch=munozsies/#$issueNumber-$branchName
echo "Stashing current changes"
git stash
echo "Creating branch $releaseBranch"
git branch $releaseBranch
git checkout $releaseBranch
git push --set-upstream origin $releaseBranch
# Switching back to the previous branch is annoying
#git checkout $branch
#git stash pop
